export const data = [
  {
    logo: '1.jpg',
    title: 'Up to $45 Off With Minimum Spend',
    todayuse: 324,
    sponsored: true,
    type: 'code',
  },
  {
    logo: '2.jpg',
    title: '15% Off Sitewide + Same Day Delivery Available',
    todayuse: 76,
    sponsored: false,
    type: 'sale',
  },
  {
    logo: '3.jpg',
    title: '25% Off $150 Min Purchase',
    todayuse: 245,
    sponsored: true,
    type: 'code',
  },
  {
    logo: '4.jpg',
    title: 'Extra 10% Off Sitewide With $30 Minimum Spend',
    todayuse: 245,
    sponsored: true,
    type: 'sale',
  },
  {
    logo: '5.jpg',
    title: 'Receive Up to $20 Off and Buy Online',
    todayuse: 545,
    sponsored: true,
    type: 'code',
  },
  {
    logo: '6.jpg',
    title: '20% Off Full Size Fragrance for Beauty Insiders',
    todayuse: 235,
    sponsored: false,
    type: 'sale',
  },
  {
    logo: '7.jpg',
    title: '$70 Off Samsung 70 Tu700d',
    todayuse: 45,
    sponsored: true,
    type: 'code',
  },
  {
    logo: '8.jpg',
    title: 'Save Up to $200 on Select Arlo Security Products',
    todayuse: 147,
    sponsored: true,
    type: 'code',
  },
  {
    logo: '9.jpg',
    title: 'Up to 75% Off + Up to Extra 10% Off Sitewide',
    todayuse: 245,
    sponsored: true,
    type: 'sale',
  },
  {
    logo: '10.jpg',
    title: 'RetailMeNot Exclusive! 25% Off Sitewide',
    todayuse: 222,
    sponsored: true,
    type: 'code',
  },
  {
    logo: '11.jpg',
    title: 'Buy 1, Get 1 Free Short Sleeve Polos',
    todayuse: 1166,
    sponsored: false,
    type: 'code',
  },
  {
    logo: '12.jpg',
    title: 'Up to 60% Off Entire Site',
    todayuse: 213,
    sponsored: true,
    type: 'code',
  },
];
